apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "khamisiapp.fullname" . }}
  labels:
    {{- include "khamisiapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "khamisiapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "khamisiapp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "khamisiapp.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      #--------------------------------
      containers:
        - name: {{ .Values.containers.container01.name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.containers.container01.image.repository }}:{{ .Values.containers.container01.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.containers.container01.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containers.container01.port }}
              protocol: TCP
        #-------------
        - name: {{ .Values.containers.container02.name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.containers.container02.image.repository }}:{{ .Values.containers.container02.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.containers.container02.image.pullPolicy }}
          ports:
            - name: {{ .Values.containers.container02.name }}
              containerPort: {{ .Values.containers.container02.port }}
              protocol: TCP
          #--------------------------
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
