apiVersion: v1
kind: Service
metadata:
  name: {{ include "khamisiapp.fullname" . }}
  labels:
    {{- include "khamisiapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.service01.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "khamisiapp.selectorLabels" . | nindent 4 }}
