apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: devops
  labels:
    deploy: app
  annotations:
    kubernetes.io/change-cause: "changing nginx image to 1.25" 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        ports:
        - containerPort: 80
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
