apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD 
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "mydatabase"
            - name: MYSQL_USER
              value: "myuser"
            - name: MYSQL_PASSWORD
              value: "mypassword"
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_REPLICATION_MODE
              value: "master"  # Default is master, slave will be configured in replication
            - name: MYSQL_REPLICATION_USER
              value: "replication_user"
            - name: MYSQL_REPLICATION_PASSWORD
              value: "replication_password"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - "mysql"
                - "-uroot"
                - "-prootpassword"
                - "-e"
                - "SELECT 1;"
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None  # Headless service to allow direct access to StatefulSet pods
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica
  namespace: default
  labels:
    app: mysql
spec:
  serviceName: "mysql-replica"
  replicas: 2
  selector:
    matchLabels:
      app: mysql-replica
  template:
    metadata:
      labels:
        app: mysql-replica
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_REPLICATION_MODE
              value: "replica"  # Replica mode for read replicas
            - name: MYSQL_REPLICATION_USER
              value: "replication_user"
            - name: MYSQL_REPLICATION_PASSWORD
              value: "replication_password"
            - name: MYSQL_MASTER_HOST
              value: "mysql-0.mysql.default.svc.cluster.local"  # Pointing to the first master pod
            - name: MYSQL_MASTER_PORT
              value: "3306"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - "mysql"
                - "-uroot"
                - "-prootpassword"
                - "-e"
                - "SELECT 1;"
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
