apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /root/.minikube/ca.crt
    server: https://192.168.49.2:8443
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: sa
  name: default-context
current-context: default-context
users:
- name: sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IldzX3JrNkp3LXVCT0hoQm1EZTJvX01TcVYzU0pXalVVSkc4cXEzbS1Rbk0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNlY3JldC1zYS1zYW1wbGUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIzOTgwNzkzMi0zNzU1LTQ1OWItYmFjMi03MjIxNjU0YTI1ODAiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpzYSJ9.SQEi8_UcXYLWWxFEFmBnenf6axYpjhL3TkYu1J1pxqrWDhthTyPZEvq0tUqpuV7Lsc3zsYJ-SYCd8lxY002BtV6V5xGJYENyC2xHgRNXtxuI0d3HGy4173NO1KPT4ZrTRcB3RRvQC-oo97osJY0qJHD086ZRfbIaiM9z7rtSTWw_Ix0_oHjs7HHN5SUZiivKHyysRy-5vOrJlzBghvp9tcxo7l_gP_E8uHnTOeb8QPOKacYvpOWdzUqJ8KU-NcV3RPJMk5Xr4jqpXDqM7SmBODd9awl-qmU7SEXStMOrjowk6EnUMhcKeHd7nOODbsau4CuX_uiwg1-dmg70UiVNng