apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: "mysql"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0  # Using MySQL 8.0 as an example
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root_password"
            - name: MYSQL_DATABASE
              value: "my_database"
            - name: MYSQL_USER
              value: "mysql_user"
            - name: MYSQL_PASSWORD
              value: "user_password"
            - name: MYSQL_REPLICATION_USER
              value: "replica"
            - name: MYSQL_REPLICATION_PASSWORD
              value: "replica_password"
            # Config for Master and Slave
            - name: MYSQL_REPLICATION_MODE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 10Gi
