apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: <base64-encoded-root-password>
  MYSQL_REPLICATION_USER: <base64-encoded-replication-user>
  MYSQL_REPLICATION_PASSWORD: <base64-encoded-replication-password>
